import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio - Kevin Castel",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}

// Represent the header
function Header(){
  return (<header className="flex content-center w-full background-color: var(--color-dark-blue) max-height-22 h-22 top-0 fixed z-1">
    <nav className="w-full h-full justify-center items-center bg-dark-blue inline-flex">
      <ul className="inline-flex w-full justify-evenly h-auto">
        <li className="text-white"><a href="/">Home</a></li>
        <li className="text-white"><a href="/experiences">Expériences</a></li>
        <li className="text-white"><a href="/projets">Projets</a></li>
      </ul>
    </nav>
  </header>)
}

// Represent the footer
function Footer(){
  const divClassName = "h-full w-full min-w-10 flex flex-col text-blue-gray-hyperlink-normal";
  const hThreeClassname = "w-full max-h-10 min-h-5 text-center text-[100%] text-blue-gray-hyperlink-normal";
  const hFourClassname = "h-auto w-full text-[80%] text-center text-blue-gray-hyperlink-normal";
  const btnTransition = "transition delay-150 duration-300 ease-in-out text-blue-gray-hyperlink-normal";
  const sizeSVG = 30;


  return (<footer className="w-full h-40 flex flex-row bg-dark-blue p-4 text-light-gray relative">
    <div className={divClassName}>
      <h3 className={hThreeClassname}>Kevin Castel</h3>
      {/* FIXME Voir pour le hover des images en couleur dorée */}
      <div className="flex h-full w-full justify-evenly items-center">
        <a href="https://linkedin.com">
          <Image className="icon" src={"/curriculum-resume-svgrepo-com.svg"} width={sizeSVG} height={sizeSVG} alt="Logo de PinkyBall"/>
        </a>
        <a href="https://www.linkedin.com/in/keviniicastel/">
          <Image className="icon" src={"/linkedin-svgrepo-com.svg"} width={sizeSVG} height={sizeSVG} alt="Logo de Linkedin"/>
        </a>
        <a href="https://github.com/KevinCastel">
          <Image className="icon" src={"/github-142-svgrepo-com.svg"} width={sizeSVG} height={sizeSVG} alt="Logo de Github"/>
        </a>
        {/* FIXME Régler le problème de couleur des icônes*/}
      </div>
    </div>
    <div className={divClassName}>
      <h3 className={hThreeClassname}>Mes projets</h3>
      <div className="h-full w-full flex flex-col justify-center  pt-1">
        <h4 className={hFourClassname}>Pinkyball</h4>
        <a className={`w-full text-center text-[78%] text-blue-gray-hyperlink-normal hover:text-blue-hyperlink-h focus:text-blue-hyerlink-focus ${btnTransition}`} href="https://invitation.itch.io/pinkyball">Accéder à PinkyBall</a>
        <h4 className={hFourClassname}>Duminombre</h4>
        <a className={`w-full text-center text-[78%] text-blue-gray-hyperlink-normal hover:text-blue-hyperlink-h focus:text-blue-hyperlink-focus ${btnTransition}`} href="https://kevincastel.github.io/duminombre/">Accéder à Duminombre</a>
      </div>
    </div>
    <div className={divClassName}>
      <h3 className={hThreeClassname}>Crédits</h3>
      <p className="h-full w-full text-center align-center pt-1 text-[80%]">All svg used here are on greppo and itch.io Pinkyball</p>
    </div>
  </footer>)
}